config/routes.rb
Store::Application.routes.draw do
  root :to => 'store#index', :via => :get
  match 'store/:product_id' => 'store#show', :as => :store_product, :via => :get
    
  match 'search_results' => 'store#search_results',
      :as => 'search_results', :via => :post
      
  match 'category/:id' => 'store#category_search', :as => 'category_search', :via => :get
  
  match 'add_sale/:id' => 'store#add_sale', :as => 'add_sale', :via => :get
  match 'remove_sale/:id' => 'store#remove_sale', :as => 'remove_sale', :via => :get
  resource :store, :only => [:index, :show] do
    member do
      get :add_sale
      get :remove_sale
    end
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  
  has_many :products
  
  validates :name, :description, presence:true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many :orders
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  
  validates :quantity, presence:true
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  has_many :products, :through => :line_items
  belongs_to :customer
  
  validates :hst_rate, :pst_rate, :gst_rate, numericality:true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price, :stock_quantity, :image_filename, :category_id
  
  belongs_to :category
  has_many :line_items
  has_many :orders, :through => :line_items
  
  validates :name, :description, :price, presence:true
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
  attr_accessible :name, :pst, :gst, :hst
  
  validates :name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/category_controller.rb
class CategoryController < InheritedResources::Base
  def category_search
    @products = Product.where("Category_id AS " + params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    @product = Product.new(user_params)
  end
  
  def user_params
    params.require(:product_id).permit(:name, :description, :price, :stock_quantity)
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  def create
    @province = User.new(user_params)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :pst, :gst, :hst)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_filter :initialize_sale  

  def index
    @products = Product.order('product_id DESC')
    @categories = Category.all
  end

  def show
    @product = Product.find(params[:product_id])
  end
  
  def category_search
    @products = Product.where("Category_id = " + params[:id])
  end
  
  def search
  end
  
  def search_results
    keywords = params[:keywords]
    
    @category = Category.where("name LIKE ?", "%#{keywords}%").first
    @products = Product.where("name LIKE ?", "%#{keywords}%")
    if @products.empty?
      @products = Product.where("category_id LIKE ?" , @category.id)
    end
  end
  
  def add_sale
    id = params[:id].to_i
    session[:buy] ||=[]
    session[:buy] << id
    redirect_to :action => :index
  end
  
  def remove_sale
    id = params[:id].to_i
    session[:buy].delete(id)
    redirect_to :action => :index
  end
  
  protected
  def initialize_sale
    session[:buy] ||=[]
    @buy = []
    session[:buy].each {|id| @buy << Product.find(id) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/categories/_category.html.erb
<p>
  <%= link_to category.name, category_search_path(category) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<%= image_tag "logo.jpg", alt: "Logo", size: "200x200"%>

<% @products.each do |product| %>
	<h3><%= product.name %></h3>
<% end %>

app/views/products/_product.html.erb
<div class = "product">
  <h2><%= link_to product.name, store_product_path(product) %></h2>

  <% if product.image_filename %>
    <p><%= image_tag product.image_filename, :width => '150', :height => '225' %></p>
  <% end %>

  <%= render :partial => 'buying', :locals => {:product => product}%>

  <p class="price">
    <%= number_to_currency product.price %>
  </p>

  <div class="description">
    <details><%= product.description %></details>
  </div>

  <% if product.category %>
    <p>
      <strong>Category:</strong> <%= product.category.name %>
    </p>
  <% end %>
</div>

app/views/store/_bought.html.erb
<div class = "cart">
  <h3>Cart</h3>

  <% if session[:buy].empty? %>
    <p>There is nothing in your cart</p>
  <% else %>
    <% @buy.each do |buy| %>
      <p>
        <%= buy.name %>
        <%= render :partial => 'buying', :locals => {:product => buy}%>
      </p>
    <% end %>
  <% end %>
</div>

app/views/store/_buying.html.erb
<% if session[:buy].include?(product.id)%>
  <%= link_to 'Remove From Cart', remove_sale_path(product) %>
<% else %>
  <%= link_to 'Add To Cart', add_sale_path(product) %>
<% end %>

app/views/store/category_search.html.erb
<%= render @products %>
<%= link_to 'Home', root_path %>

app/views/store/index.html.erb
<header>
  <%= image_tag "logo.jpg", alt: "Logo", size: "200x200"%>

  <%= form_tag search_results_path do %>
     <div class="col-lg-6">
        <div class="input-group">
  	  <%= text_field_tag :keywords %>
          <span class="input-group-btn">
            <%= submit_tag 'Search', :class => "btn btn-default" %>
          </span>
        </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  <% end %>
  <p>
    <br /><nav><%= render@categories%></nav>
  </p>
</header>
<%= render 'bought' %>

<%= render@products%>

<footer>
  Developed by: Steven Hanson
</footer>

app/views/store/search.html.erb
<h2>Product Search</h2>

<%= form_tag search_results_path do %>
  <%= text_field_tag :keywords %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/store/search_results.html.erb
<h2>Search Results</h2>

<% if @products.empty? %>
  <p>
    Sorry your search for '<%= params[:keywords] %>' returned no results.
  </p>
<% end %>

<%= render @products %>

app/views/store/show.html.erb
<%= render @product %>

<p>
  <%= link_to 'Home', root_path %>
</p>